network:
    ethernets:
        ens18:
            addresses:
            - 192.168.1.101/24
            gateway4: 192.168.1.1
            nameservers:
                addresses:
                - 1.1.1.1
                - 1.0.0.1
    version: 2
